executable              = /afs/cern.ch/work/j/jthomasw/private/NTU/fast_sim/tdsm_encoder/condor_scripts/run_tdsm.sh
output                  = run_tdsm.$(ClusterId).$(ProcId).out
error                   = run_tdsm.$(ClusterId).$(ProcId).err
log                     = run_tdsm.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 4
+JobFlavour = "nextweek"
queue
