executable              = ../condor_scripts/run_pad_events.sh
output                  = run_tdsm.$(ClusterId).$(ProcId).out
error                   = run_tdsm.$(ClusterId).$(ProcId).err
log                     = run_tdsm.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
+JobFlavour = "longlunch"
arguments               = $Fnx(filename)
queue filename matching (/eos/user/t/tihsu/database/ML_hackthon/bucketed_tensor/dataset_2_tensor_no_pedding_euclidian*.pt)